### ISSUE TITLE
unable to run exe file in cmd 

### ISSUE THREAD

**Issue by lokeshpaladugula** [rohinibarla/dev#13]
while i have compiled the program and tries to run the executable file, im getting an error like 
ERROR:
"  This version of C:\Users\win\Documents\a.exe  is not compatible with the version
of Windows you're running. Check your computer's system information to see wheth
er you need a x86 (32-bit) or x64 (64-bit) version of the program, and then cont
act the software publisher. "

![ERROR_MSG](https://user-images.githubusercontent.com/45807323/57781373-aff58f80-7747-11e9-951c-b8d46c06d2cc.png)

**Comment by lokeshpaladugula** [comment]
solution:
Here, the gcc i am using is 64bit , and my windows is 32 bit.
Now in order to compile with 32-bit gcc, just add a flag -m32 in the command line while compling the ‘C’ language program.
![ERROR_MSG](https://user-images.githubusercontent.com/45807323/57781785-7ffabc00-7748-11e9-9257-ccb515c24041.png)

it generates the 32bit executable file.

**Comment by rohinibarla** [comment]
similarly to generate 64 bit executable, use -m64 option for gcc when needed,
