### ISSUE TITLE
function declaration issue

### ISSUE THREAD

**Issue by AmeerCh** [rohinibarla/dev#5]
line1: void delete_char(char*, int);  
          int main(){
             chat str[100];
             int index;
              -------
          } 
line2: void delete-char(char *str, int index){
          ---------
          }  

**// This program was executed, but line 1 in function definition we are declaring only data types, //but not declared variable names. so what will be happening there?**

**Comment by Akhilpilli** [comment]
What I know is that at line 1 we are specifying to that the function will get a char and int values as parameters even if we don't keep variable name's there will be no different from "void delete-char(char *string, int index);".
void delete-char(char *string, int index);
if we declare the above line as line 1 then we have to use the same variables(string, index) at the time of implementation at line 2.

or 
if you just used "void delete_char(char*, int);"  as line one then
We can decide the variable name's at the time of implementation's(at line 2)

**Comment by rohinibarla** [comment]
variable names for the arguments of a function are required only in definition (implementation) of the function. In a declaration, only the types are sufficient. So that is the reason for this behavior.
