### ISSUE TITLE
output assignment

### ISSUE THREAD

**Issue by DivyaSaiSahiti** [rohinibarla/dev#6]
is there any way to store the output of a printf() into a variable or an array?

**Comment by rohinibarla** [comment]
Yes, it is possible using sprintf() to print into a char array.
Similarly, you can read from a string using sscanf().

e.g: check: https://www.geeksforgeeks.org/sprintf-in-c/

**Comment by rohinibarla** [comment]
sscanf and sprintf are the functions for this purpose only.
