### ISSUE TITLE
format specifier

### ISSUE THREAD

**Issue by lrenuka** [rohinibarla/dev#7]
After reading any string or number, its not reading a character even when I am using 
scanf("%c",  &ch);  why?

**Comment by rohinibarla** [comment]
Check this and experiment with different inputs

https://stackoverflow.com/a/13543113

**Comment by rohinibarla** [comment]
scanf behavior is like this, make sure you don't get stuck in such situations. Use the workaround specified.

**Comment by rohinibarla** [comment]
See: Why does everyone say not to use scanf? What should I use instead?

http://c-faq.com/stdio/scanfprobs.html
