### ISSUE TITLE
size_t ?

### ISSUE THREAD

**Issue by manikanta96** [rohinibarla/dev#8]
size_t alloc_length = 1024;
is that size_t a data type? If so, in what cases it is used?

**Comment by rohinibarla** [comment]
size_t is type defined.

if the compiler is 32 bit then it is simply a typedef(i.e., alias) for unsigned int but if the compiler is 64 bit then it would be a typedef for unsigned long long. The size_t data type is never negative.

malloc, memset, fwrite... memory related operations, where you specify the number of bytes, which can be positive only. In these methods size_t is used.
